/* FILE GENERATED AUTOMATICALLY */

export type Agents =
    | "Gekko"
    | "Fade"
    | "Breach"
    | "Deadlock"
    | "Raze"
    | "Chamber"
    | "KAY/O"
    | "Skye"
    | "Cypher"
    | "Sova"
    | "Killjoy"
    | "Harbor"
    | "Viper"
    | "Phoenix"
    | "Astra"
    | "Brimstone"
    | "Iso"
    | "Neon"
    | "Yoru"
    | "Sage"
    | "Reyna"
    | "Omen"
    | "Jett";
