/* FILE GENERATED AUTOMATICALLY */

export type BuddyType =
    | "Task Force 809 Buddy"
    | "Beckoner Buddy"
    | "RGX 11z Pro Buddy"
    | "RGX 11z Pro, Ep 4 Buddy"
<<<<<<< Updated upstream
=======
    | "Cruiser Buddy"
    | "Big Announcement Buddy"
    | "Altitude Buddy"
    | "Anansi Buddy"
    | "Araxys Buddy"
    | "Epilogue: Apple a Day Buddy"
>>>>>>> Stashed changes
    | "Neptune Buddy"
    | "Gaia's Vengeance Buddy"
    | "Gaia's Vengeance, Ep 7 Buddy"
    | "Zedd Buddy"
    | "Get Carried Buddy"
    | "Composite Buddy"
    | "Alley-oop Buddy"
    | "Epilogue: Alley-oop Buddy"
    | "Night Guard Buddy"
    | "Bazooka Badger Buddy"
    | "Big Brain Buddy"
    | "In A Bind Buddy"
    | "Year One Buddy"
    | "Apple a Day Buddy"
    | "BlastX Buddy"
    | "Blueberry Buddy"
    | "Boba Buddy"
    | "Nazar Bead Buddy"
    | "Hammer Time Buddy"
    | "Big ol' Barrel Buddy"
    | "Easy Breezy Buddy"
    | "Ornamental Commander Buddy"
    | "Bruno Coin Buddy"
    | "Epilogue: Bruno Coin Buddy"
    | "Eco the Bulldog Buddy"
    | "Epilogue: Eco the Bulldog Buddy"
    | "Bullet Buddy"
    | "Call Me Buddy"
    | "Closed Beta Coin Buddy"
    | "Nanowire Cartridge Buddy"
    | "Desert Rose Buddy"
    | "Crunch the Numbers Buddy"
    | "Get The Picture Buddy"
    | "Let It Cook Buddy"
    | "Edible Ornament Buddy"
    | "Cat-Eye Buddy"
    | "VALORANT GO! Vol. 1 Cypher Buddy"
    | "VALORANT GO! Vol. 1 Jett Buddy"
    | "VALORANT GO! Vol. 1 Killjoy Buddy"
    | "VALORANT GO! Vol. 2 Phoenix Buddy"
    | "VALORANT GO! Vol. 2 Raze Buddy"
    | "VALORANT GO! Vol. 1 Reyna Buddy"
    | "VALORANT GO! Vol. 1 Sage Buddy"
    | "VALORANT GO! Vol. 2 Sova Buddy"
    | "VALORANT GO! Vol. 2 Viper Buddy"
    | "VALORANT GO! Vol. 2 Yoru Buddy"
    | "Winner Winner Buddy"
    | "Good Luck Knot Buddy"
    | "Chicken Out Buddy"
    | "Origin Buddy"
    | "Blast Pin Buddy"
    | "Island Dreams Buddy"
    | "Rune Stone Buddy"
    | "EP 1 // 1 Coin Buddy"
    | "EP 1 // 2 Coin Buddy"
    | "EP 1 // 3 Coin Buddy"
    | "EP 2 // 1 Coin Buddy"
    | "EP 2 // 2 Coin Buddy"
    | "EP 2 // 3 Coin Buddy"
    | "EP 3 // 1 Coin Buddy"
    | "Ep 3 // 2 Coin Buddy"
    | "Ep 3 // 3 Coin Buddy"
    | "Ep 4 // 1 Coin Buddy"
    | "Ep 4 // 2 Coin Buddy"
    | "EP 4 // 3 Coin Buddy"
    | "Ep 5 // 1 Coin Buddy"
    | "Ep 5 // 2 Coin Buddy"
    | "Ep 5 // 3 Coin Buddy"
    | "Ep 6 // 1 Coin Buddy"
    | "Ep 6 // 2 Coin Buddy"
    | "Ep 6 // 3 Coin Buddy"
    | "Ep 7 // 1 Coin Buddy"
    | "Ep 7 // 2 Coin Buddy"
    | "Ep 7 // 3 Coin Buddy"
    | "Ep 8 // 1 Coin Buddy"
    | "Follow Me Buddy"
    | "Shell Song Buddy"
    | "Epilogue: Shell Song Buddy"
    | "Corbin's Light Buddy"
    | "Chilly McFreeze Buddy"
    | "Completely Cracked Buddy"
    | "Crate Buddy"
    | "Radianite Crate Buddy"
    | "Red Alert Buddy"
    | "Cup o' Crown Buddy"
    | "Prime Time Buddy"
    | "Slurp Buddy"
    | "Arcane Cupcake Buddy"
    | "Electric Love Buddy"
    | "Divine Swine Buddy"
    | "Potted Pal Buddy"
    | "Glitchpop Buddy"
    | "Glitchpop, EP 2 Buddy"
    | "Champions 2022 Dad Hat Buddy"
    | "ChronoVoid Buddy"
    | "Dalgona Coffee Buddy"
    | "Dance Fever Buddy"
    | "Danger Lizard Buddy"
    | "Shoot Here Buddy"
    | "Daruma Charm Buddy"
    | "Prelude to Chaos Buddy"
    | "Lucky Dice Buddy"
    | "Discotech Buddy"
    | "Epilogue: Discotech Buddy"
    | "Outlaw Buddy"
    | "Donut Buddy"
    | "Elderflame Buddy"
    | "Ion, Ep5 Buddy"
    | "VLT/R Buddy"
    | "Ragna-Rock Out Buddy"
    | "Ducky on Swing Buddy"
    | "Happy Dumpling Buddy"
    | "Dumpster Fire Buddy"
    | "Epilogue: Dumpster Fire Buddy"
    | "Imperium Buddy"
    | "Egg in a Basket Buddy"
    | "Singularity Buddy"
    | "Sunny Side Buddy"
    | "Epilogue: Sunny Side Buddy"
    | "Music Electric Buddy"
    | "Songsteel Buddy"
    | "Together Forever Buddy"
    | "Champions Cube Buddy"
    | "VCT LOCK//IN Winner Buddy"
    | "VCT Champions Winner Buddy"
    | "VCT Masters Winner Buddy"
    | "VCT 2021 Spark Buddy"
    | "Good Boy, Bruno Buddy"
    | "Venturi Buddy"
    | "Nice Smile Buddy"
    | "Hundreds and Thousands Buddy"
    | "Forsaken Buddy"
    | "Ups and Downs Buddy"
    | "Velocity Buddy"
    | "Topotek Buddy"
    | "K.nock O.ut!! Buddy"
    | "Lunar Firework Buddy"
    | "Ascent Rising Buddy"
    | "Arcane Poro Buddy"
    | "Team Ace Buddy"
    | "KNG Meridian Buddy"
    | "Deep Divisions Buddy"
    | "Le Baguette Buddy"
    | "Kiss the Frog Buddy"
    | "Froggie Hat Buddy"
    | "Spectrum Buddy"
    | "Tactical Surprise Buddy"
    | "Game Changers Winner Buddy"
    | "Game Changers Trophy Buddy"
    | "Penguin Surprise Buddy"
    | "Epilogue: Penguin Surprise Buddy"
    | "Gelato Cutie Buddy"
    | "Gimbap Buddy"
    | "Tall Tales Buddy"
    | "Give Back Buddy"
    | "Give Back // 2023 Buddy"
    | "Terrarium Treasure Buddy"
    | "Shimmer Buddy"
    | "Caught Buddy"
    | "Ruin Watcher Buddy"
    | "Memory Chip Buddy"
    | ".SYS Buddy"
    | "Hawko Buddy"
    | "White Hat Buddy"
    | "Neo Frontier Buddy"
    | "Halo Halo Buddy"
    | "Ready to Roll Buddy"
    | "Safe Haven Buddy"
    | "Xpert Comms Buddy"
    | "Digihex Buddy"
    | "Owl Charm Buddy"
    | "Hydrodip Buddy"
    | "Prime Buddy"
    | "Prime//2.0 Buddy"
    | "Frozen Solid Buddy"
    | "Icy Crate Buddy"
    | "Premier Ignition Champion Buddy"
    | "Bound Buddy"
    | "Mi Goreng Buddy"
    | "VCT LOCK//IN Dad Hat Buddy"
    | "Jack O' Lantern Buddy"
    | "Give Back // 2022 Buddy"
    | "Extra Crispy Buddy"
    | "Heavy Lifting Buddy"
    | "The Key to Ancient Mysteries Buddy"
    | "Key of Life Buddy"
    | "Bot Buddy"
    | "Netter Treter Buddy"
    | "Ruination Buddy"
    | "K/TAC Buddy"
    | "Kingdom Logo Buddy"
    | "Kitsune Mask Buddy"
    | "Neural Pattern Buddy"
    | "Perfect Pattern Buddy"
    | "Bumble Stitch Buddy"
    | "Kohaku & Matsuba Buddy"
    | "Miss Spots Buddy"
    | "Dance of Luck Buddy"
    | "Blush Buddy"
    | "Daydreams Buddy"
    | "Iridian Thorn Buddy"
    | "Star Lotus Buddy"
    | "GL Have Cat Buddy"
    | "New Year's Knot Buddy"
    | "Celestial Buddy"
    | "Magepunk Buddy"
    | "Magepunk, Ep 6 Buddy"
    | "Magic Hummingbird Buddy"
    | "Spline Buddy"
    | "On The Case Buddy"
    | "Magic Mance Buddy"
    | "Mango Tango Buddy"
    | "Time's Up Buddy"
    | "Dallah Buddy"
    | "Mic Drop Buddy"
    | "Bounce House Buddy"
    | "Monkey Business Buddy"
    | "Valiant Hero Buddy"
    | "Monster Cookie Buddy"
    | "Hot and Spicy Buddy"
    | "Drop the Hammer Buddy"
    | "Epilogue: Drop the Hammer Buddy"
    | "Mid-Autumn Sweet Buddy"
    | "Overdrive Buddy"
    | "Treble Clef Buddy"
    | "Epilogue: Treble Clef Buddy"
    | "Matryoshka Buddy"
    | "Genesis Buddy"
    | "Salmon Nigiri Buddy"
    | "Moondash Buddy"
    | "Kuronami Buddy"
    | "Deadly Precision Buddy"
    | "Libretto Buddy"
    | "Ion Buddy"
    | "Ancient Mysteries Revealed Buddy"
    | "VALORANT Coin Buddy"
    | "Oni Buddy"
    | "Oni, Ep 6 Buddy"
    | "Keep it Safe Buddy"
    | "Keep it Safer Buddy"
    | "Venom Vial Buddy"
    | "Folded Wish Buddy"
    | "Epilogue: Folded Wish Buddy"
    | "Peace and Love Buddy"
    | "Mother of Pearl Buddy"
    | "Dan the Penguin Buddy"
    | "Hot Bling Buddy"
    | "High Top Heat Buddy"
    | "Can't Break Me Buddy"
    | "Hue Shift Buddy"
    | "Old Salt Buddy"
    | "Pocket Sage Buddy"
    | "Pizza Buddy"
    | "Magepunk, Ep 3 Buddy"
    | "POLYfox Buddy"
    | "Rubber Ducky Buddy"
    | "Artisan Buddy"
    | "Take on the Tundra Buddy"
    | "PREMIER E7A3 CHAMPION // ADV BUDDY"
    | "PREMIER E7A3 CHAMPION // CTD BUDDY"
    | "PREMIER E7A3 CHAMPION // ELT BUDDY "
    | "PREMIER E7A3 CHAMPION // INT BUDDY"
    | "PREMIER E7A3 CHAMPION // OPN BUDDY"
    | "Premier Launch Champion // Adv Buddy"
    | "Premier Launch Champion // Ctd Buddy"
    | "Premier Launch Champion // Elt Buddy "
    | "Premier Launch Champion // Int Buddy"
    | "Premier Launch Champion // Opn Buddy"
    | "Pay Respects Buddy"
    | "One Direction Buddy"
<<<<<<< Updated upstream
    | "Pride 2022 Buddy"
=======
    | "Pride Buddy"
>>>>>>> Stashed changes
    | "Protocol 781-A Buddy"
    | "Original Protractor Buddy"
    | "Lovebyte Gun Buddy"
    | "Lucky Rabbit Buddy"
    | "Radianite Crystal Buddy"
    | "Late Night Calories Buddy"
    | "EP1: Bronze Buddy"
    | "EP1: Diamond Buddy"
    | "EP1: Gold Buddy"
    | "EP1: Immortal Buddy"
    | "EP1: Iron Buddy"
    | "EP1: Platinum Buddy"
    | "EP1: Radiant Buddy"
    | "EP1: Silver Buddy"
    | "EP2: Bronze Buddy"
    | "EP2: Diamond Buddy"
    | "EP2: Gold Buddy"
    | "EP2: Immortal Buddy"
    | "EP2: Iron Buddy"
    | "EP2: Platinum Buddy"
    | "EP2: Radiant Buddy"
    | "EP2: Silver Buddy"
    | "EP3: Bronze Buddy"
    | "EP3: Diamond Buddy"
    | "EP3: Gold Buddy"
    | "EP3: Immortal Buddy"
    | "EP3: Iron Buddy"
    | "EP3: Platinum Buddy"
    | "EP3: Radiant Buddy"
    | "EP3: Silver Buddy"
    | "EP4: Bronze Buddy"
    | "EP4: Diamond Buddy"
    | "EP4: Gold Buddy"
    | "EP4: Immortal Buddy"
    | "EP4: Iron Buddy"
    | "EP4: Platinum Buddy"
    | "EP4: Radiant Buddy"
    | "EP4: Silver Buddy"
    | "EP5: Ascendant Buddy"
    | "EP5: Bronze Buddy"
    | "EP5: Diamond Buddy"
    | "EP5: Gold Buddy"
    | "EP5: Immortal Buddy"
    | "EP5: Iron Buddy"
    | "EP5: Platinum Buddy"
    | "EP5: Radiant Buddy"
    | "EP5: Silver Buddy"
    | "EP6: Ascendant Buddy"
    | "EP6: Bronze Buddy"
    | "EP6: Diamond Buddy"
    | "EP6: Gold Buddy"
    | "EP6: Immortal Buddy"
    | "EP6: Iron Buddy"
    | "EP6: Platinum Buddy"
    | "EP6: Radiant Buddy"
    | "EP6: Silver Buddy"
    | "EP7: Ascendant Buddy"
    | "EP7: Bronze Buddy"
    | "EP7: Diamond Buddy"
    | "EP7: Gold Buddy"
    | "EP7: Immortal Buddy"
    | "EP7: Iron Buddy"
    | "EP7: Platinum Buddy"
    | "EP7: Radiant Buddy"
    | "EP7: Silver Buddy"
    | "Gravitational Uranium Neuroblaster Buddy"
    | "Slay Ride Buddy"
    | "Panoramic Buddy"
    | "Stardust Buddy"
    | "Robotic Companion Buddy"
    | "Flash Blades Buddy"
    | "Root Beer Buddy"
    | "Immortal Rose Buddy"
    | "Sentinels of Light, Ep 7 Buddy"
    | "Salt Shaker Buddy"
    | "Epilogue: Salt Shaker Buddy"
    | "Ancient Inheritance Buddy"
    | "Dog Tags Buddy"
    | "Sunset Scoot Buddy"
    | "Seal of Approval Buddy"
    | "Peripherals Buddy"
    | "Silhouette Buddy"
    | "Fishbones Buddy"
    | "Pocket Sized Sheriff Buddy"
    | "Epilogue: Pocket Sized Sheriff Buddy"
    | "Knight's Market Buddy"
    | "Swinging Shumai Buddy"
    | "Lycan's Bane Buddy"
    | "Transition Buddy"
    | "All-purpose Slipper Buddy"
    | "Winter Whisper Buddy"
    | "Snowbro Buddy"
    | "Snowfall Buddy"
    | "Sentinels of Light Buddy"
    | "Reaver Buddy"
    | "Reaver, EP 5 Buddy"
    | "Sovereign Buddy"
    | "Hot Take Buddy"
    | "The Spike Buddy"
    | "Spike Rush Buddy"
    | "Split Decision Buddy"
    | "Battle Crab Buddy"
    | "Surge Protector Buddy"
    | "Lucky Star Buddy"
    | "Epilogue: Lucky Star Buddy"
    | "Dimensional Fragment Buddy"
    | "Sock of Cheer Buddy"
    | "Tilde Buddy"
    | "Riptide Buddy"
    | "Cheesed Buddy"
    | "On The Low Buddy"
    | "Bear Tactics Buddy"
    | "Hula Bear Buddy"
    | "Bunny Tactics Buddy"
    | "UltraBright Torch Buddy"
    | "Cat Tactics Buddy"
    | "Hang Time Buddy"
    | "Squirrel Tactics Buddy"
    | "Potato Aim Buddy"
    | "Sample 36-K Buddy"
    | "Radianite Orb Buddy"
    | "Tigris Buddy"
    | "Toaster Buddy"
    | "NO LIMITS Buddy"
    | "Octobuddy Buddy"
    | "Scuttle Trash Buddy"
    | "Fist Bump Buddy"
    | "Sandswept Buddy"
    | "Champions 2022 Buddy"
    | "Turtle Ship Buddy"
    | "No. 1 Fan Buddy"
    | "Tower of Power Buddy"
    | "Outta This World Buddy"
    | "Exquisitely Wrapped Buddy"
    | "Stringed Soprano Buddy"
    | "Ego Buddy"
    | "The Wheel of Steel Buddy"
    | "Soul Capsule Buddy"
    | "Walis Tambo Buddy"
    | "Luna Buddy"
    | "White Snake Buddy"
    | "Grim Delight Buddy"
    | "Pocket Knife Buddy"
    | "PlayZilla Trick Master Buddy"
    | "Dimensional Drip Buddy"
    | "Zoomer Pop Buddy";
